[colors.bright]
black = "#080808"
blue = "#00afff"
cyan = "#8be9fd"
green = "#87ffaf"
magenta = "#ff00af"
red = "#ff0000"
white = "#dadada"
yellow = "#ffaf00"

[colors.normal]
black = "#080808"
blue = "#00afff"
cyan = "#8be9fd"
green = "#87ffaf"
magenta = "#ff00af"
red = "#ff0000"
white = "#dadada"
yellow = "#ffaf00"

[colors.primary]
background = "#282a36"
foreground = "#D3D7CF"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Source Code Pro"

[font.italic]
family = "Source Code Pro"

[font.normal]
family = "Source Code Pro"

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 0.85

[terminal]
